[project]
name = "pyutils-astashkevich"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "frozendict>=2.4.7",
    "pandera>=0.27.0",
]
